# SPDX-License-Identifier: GPL-2.0
#
# Makefile for the Xilink network device drivers.
#

obj-$(CONFIG_SOLID_DUMMY_NET) += solid_dummy_main.o
obj-$(CONFIG_SOLID_DUMMY_NET) += solid_dummy_netdev.o
obj-$(CONFIG_SOLID_DUMMY_NET) += solid_dummy_ethtool.o
